<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>小贝管理平台 | <?echo $title;?></title>

    <!-- Bootstrap -->
    <link href="/bower_components/gentelella/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="/bower_components/gentelella/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="/bower_components/gentelella/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- jQuery custom content scroller -->
    <link href="/bower_components/gentelella/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css" rel="stylesheet"/>
    <!-- Switchery -->
    <link href="/bower_components/gentelella/vendors/switchery/dist/switchery.min.css" rel="stylesheet">
    <!-- Custom Theme Style -->
    <link href="/bower_components/gentelella/build/css/custom.min.css" rel="stylesheet">
    <!-- Dropzone.js -->
    <link href="/bower_components/gentelella/vendors/dropzone/dist/min/dropzone.min.css" rel="stylesheet">

    <link href="/bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css">
</head>

<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <?echo $current->sidebarTemplate()?>
        <?echo $current->headerTemplate()?>

        <!-- page content -->
        <div class="right_col" role="main">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>新建<small></small></h2>

                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content" >
                        <br>
                        <form id="demo-form2" data-parsley-validate="" action="" class="form-horizontal form-label-left" novalidate="" method="post">
                            <?foreach($fields as $key => $field){
                                switch($field["type"]){
                                    case "file":?>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="post-<?echo $key?>">
                                                <?echo $field["label"]?>
                                            </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <div><?echo $field["data"]?></div>
                                                <div id="-<?echo $key?>" action="/file/upload" class="dropzone"></div>
                                                <input type="hidden" id="post-<?echo $key?>" name="post-<?echo $key?>">
                                            </div>
                                        </div>
                                        <?break;
                                    case "select":?>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="post-<?echo $key?>">
                                                <?echo $field["label"]?>
                                            </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">

                                                <select class="form-control col-md-7 col-xs-12" name="post-<?echo $key?>">
                                                    <?foreach($field["options"] as $key => $option){?>
                                                        <option value="<?echo $key?>" <?echo $field["data"] == $key?"selected":""?>><?echo $option?></option>
                                                    <?}?>
                                                </select>
                                            </div>
                                        </div>
                                        <?break;
                                    case "boolean":?>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="post-<?echo $key?>">
                                                <?echo $field["label"]?>
                                            </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12" style="padding-top: 5px;">
                                                <input type="checkbox" class="js-switch" id="post-<?echo $key?>" <?echo $field["data"] == 1?"checked":""?> />
                                            </div>
                                        </div>
                                        <?break;
                                    case "many_to_one":?>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="post-<?echo $key?>">
                                                <?echo $field["label"]?>
                                            </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <div style="float: left;">
                                                    <input class="form-control" style="height: 32px;" type="text" id="post-<?echo $key?>-data" name="post-<?echo $key?>-data" readonly value="">
                                                    <input type="hidden" id="post-<?echo $key?>" name="post-<?echo $key?>" value="">
                                                    <input type="hidden" id="post-<?echo $key?>-refer" name="post-<?echo $key?>-refer" value="<?echo $field["id"]?>">
                                                    <input type="hidden" id="post-<?echo $key?>-show" name="post-<?echo $key?>-show" value="<?list($none, $field_name) = explode(".", $key);echo $field_name;?>">
                                                </div>
                                                <div style="float: left;">
                                                    <a id="post-<?echo $key?>-remove" class="glyphicon glyphicon-remove btn remove_many_to_one"style="pointer-events: auto; margin-top: -2px;"></a>
                                                    <button id="post-<?echo $key?>" name="post-<?echo $key?>" style="height: 32px;margin-left: 16px;" class="btn btn-default many_to_one">选择</button>
                                                    <input type="hidden" id="post-<?echo $key?>-url" value="<?echo $field["url"]?>">
                                                </div>
                                            </div>
                                        </div>
                                        <?break;
                                    case "datetime":?>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="post-<?echo $key?>">
                                                <?echo $field["label"]?>
                                            </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12" style="padding-top: 5px;">
                                                <input type="text" name="post-<?echo $key?>" id="post-<?echo $key?>" class="form-control datetime" value="<?echo $field['data']?>"/>

                                            </div>
                                        </div>
                                        <?break;
                                    case "hidden":?>
                                        <input type="hidden" id="post-<?echo $key?>" name="post-<?echo $key?>" value="<?echo $field["data"]?>" required="required" class="form-control col-md-7 col-xs-12">
                                        <?break;
                                    default:?>
                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12" for="post-<?echo $key?>">
                                                <?echo $field["label"]?>
                                            </label>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <input type="text" id="post-<?echo $key?>" name="post-<?echo $key?>" value="<?echo $field["data"]?>" required="required" class="form-control col-md-7 col-xs-12">
                                            </div>
                                        </div>
                                    <?}
                            }?>
                            <div class="ln_solid"></div>
                            <input type="hidden" name="<?echo $this->security->getTokenKey() ?>" value="<?echo $this->security->getToken() ?>"/>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <a href="<?echo "/$current->controller/list"?>" class="btn btn-primary" type="button">取消</a>
                                    <button class="btn btn-primary" type="reset">重置</button>
                                    <button type="submit" class="btn btn-success">提交</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- /page content -->
        <?echo $footerTemplate?>
    </div>
</div>
<div id="show_mask_parent" style="z-index: 999;position: fixed; display: none;width: 90%;height: 90%;top: 5%;left: 5%;">
    <img id="child-close" src="/img/close.png" style="position: fixed;top: 7%;right: 8%;width: 32px;height: 32px;">
    <div  id="show_mask" style="width: 100%;height: 100%;"></div>
</div>
<!-- jQuery -->
<script src="/bower_components/gentelella/vendors/jquery/dist/jquery.min.js"></script>
<!-- Dropzone.js -->
<script src="/bower_components/gentelella/vendors/dropzone/dist/min/dropzone.min.js"></script>
<!-- Bootstrap -->
<script src="/bower_components/gentelella/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Switchery -->
<script src="/bower_components/gentelella/vendors/switchery/dist/switchery.min.js"></script>
<!-- FastClick -->
<script src="/bower_components/gentelella/vendors/fastclick/lib/fastclick.js"></script>
<!-- NProgress -->
<script src="/bower_components/gentelella/vendors/nprogress/nprogress.js"></script>
<!-- jQuery custom content scroller -->
<script src="/bower_components/gentelella/vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>

<script src="/bower_components/gentelella/vendors/iCheck/icheck.min.js"></script>
<!-- Custom Theme Scripts -->
<script src="/bower_components/gentelella/build/js/custom.min.js"></script>

<script src="/bower_components/moment/min/moment-with-locales.min.js"></script>

<script src="/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
<script>
    Dropzone.autoDiscover = false;
    $(".datetime").datetimepicker({format:'YYYY-MM-DD HH:mm', locale:'zh-cn'});

    $(".dropzone").each(function(){
        var id = $(this).attr("id");
        $(this).dropzone({
            url: "/file/uploadReturnUrl",
            maxFiles: 1,
            success : function(file, response){
                $("#post"+id).val(response);
            }
        });
    });

    $(".many_to_one").click(function(event){
        var id = $(this).attr("id");
        var url_id = "#" + id + "-url";
        var show_id = "#" + id + "-show";

        var url = $(url_id.replace("\.", "\\\.")).val();
        var show = $(show_id.replace("\.", "\\\.")).val();

        url += "&key="+id+"&data="+id+"-data&show=" + show;
        console.log(url);
        $("#show_mask").html('<iframe style="width: 100%; height: 100%;" src="' + url + '"></iframe>');
        $("#show_mask_parent").css("display", "block");
        $("#child-close").css("display", "block");
        event.preventDefault();
    });

    $(".remove_many_to_one").click(function(event){
        var id = $(this).attr("id").replace("-remove", "");
        var data_id = id + "-data";
        $("#" + id.replace("\.", "\\\.")).attr("value", "");
        $("#" + data_id.replace("\.", "\\\.")).attr("value", "");
        event.preventDefault();
    });

    $("#child-close").click(function(event){
        $("#show_mask").html('');
        $("#show_mask_parent").css("display", "none");
        $("#child-close").css("display", "none");
    });

</script>

</body>
</html>